### PR TITLE
Add files made with split level 0

### PR DESCRIPTION
**Pull request by wddgit**
See PR cms-sw/cmssw#46044 for a description. This PR should be merged together with that one or the related unit test will fail. The PR test for that other PR tests this one.

### CODE REVIEW

**Comment by smuzaffar** [comment]
+externals

data files for new unit tests

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
+l1

**Comment by smuzaffar** [comment]
@aloeliger , no need to test it here. It has been already tested via [cms-sw/cmssw#46044 ](https://github.com/cms-sw/cmssw/pull/46044)

**Comment by aloeliger** [comment]
please abort

**Comment by mandrenguyen** [comment]
+1

**Comment by mandrenguyen** [comment]
merge

**Comment by smuzaffar** [comment]
@mandrenguyen , I think these data PRs ( mentioned here https://github.com/cms-sw/cmssw/pull/46044#issuecomment-2361933998 ) should be merged along with the cms-sw/cmssw#46044 otherwise unit tests in IB might fail

**Comment by makortel** [comment]
> I think these data PRs ( mentioned here [cms-sw/cmssw#46044 (comment)](https://github.com/cms-sw/cmssw/pull/46044#issuecomment-2361933998) ) should be merged along with the [cms-sw/cmssw#46044](https://github.com/cms-sw/cmssw/pull/46044) otherwise unit tests in IB might fail

Yes!

**Comment by mandrenguyen** [comment]
Thanks, I think I got them all

**Comment by makortel** [comment]
Sorry for being unclear. The https://github.com/cms-sw/cmssw/pull/46044 was still being reviewed, so the data PRs should not have been merged yet. Maybe we can get https://github.com/cms-sw/cmssw/pull/46044 signed soon.

**Pull request merged**
